spring:
  application:
    name: event-reload
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
        monitoring-secrets: true
        strategy: refresh
        mode: event
        monitoring-configMaps: false
      config:
        enabled: false
      secrets:
        enabled: true

  # otherwise we can't refresh in the test
  main:
    cloud-platform: kubernetes


